### ISSUE TITLE
Выравнивайте код: Ctrl + Alt + L в IDEA

### ISSUE THREAD

**Issue by coursar** [RuselSam/fuelConsumption#3]
https://github.com/RuselSam/itpark.homework/blob/eec88f0d9385f1498596379e636a088f22918ee1/src/main/java/fuelConsumption.java#L5-L12

**Comment by RuselSam** [comment]
выровнял код комбинацией ctrl+alt+L

**Comment by coursar** [comment]
не видно, пробелы не появились
